/* Associates an Ability with a particular number. Mostly for the
 * Ability combobox; CalculateDamage handles the actual effects. */

package superDamageCalculator;
import java.util.HashMap;

public class Abilitydex
{
	public HashMap<String, Integer> abilities = new HashMap<String, Integer>();

	public Abilitydex()
	{
		init();
	}

	public void init()
	{
		abilities.put("Adaptability", 0);
		abilities.put("Aerilate", 1);
		abilities.put("Aftermath", 2);
		abilities.put("Air Lock", 3);
		abilities.put("Analytic", 4);
		abilities.put("Anger Point", 5);
		abilities.put("Anticipation", 6);
		abilities.put("Arena Trap", 7);
		abilities.put("Aroma Veil", 8);
		abilities.put("Aura Break", 9);
		abilities.put("Bad Dreams", 10);
		abilities.put("Battery", 11);
		abilities.put("Battle Armor", 12);
		abilities.put("Battle Bond", 13);
		abilities.put("Beast Boost", 14);
		abilities.put("Berserk", 15);
		abilities.put("Big Pecks", 16);
		abilities.put("Blaze", 17);
		abilities.put("Bulletproof", 18);
		abilities.put("Cheek Pouch", 19);
		abilities.put("Chlorophyll", 20);
		abilities.put("Clear Body", 21);
		abilities.put("Cloud Nine", 22);
		abilities.put("Color Change", 23);
		abilities.put("Comatose", 24);
		abilities.put("Competitive", 25);
		abilities.put("Compound Eyes", 26);
		abilities.put("Contrary", 27);
		abilities.put("Corrosion", 28);
		abilities.put("Cursed Body", 29);
		abilities.put("Cute Charm", 30);
		abilities.put("Damp", 31);
		abilities.put("Dancer", 32);
		abilities.put("Dark Aura", 33);
		abilities.put("Dazzling", 34);
		abilities.put("Defeatist", 35);
		abilities.put("Defiant", 36);
		abilities.put("Delta Stream", 37);
		abilities.put("Desolate Land", 38);
		abilities.put("Disguise", 39);
		abilities.put("Download", 40);
		abilities.put("Drizzle", 41);
		abilities.put("Drought", 42);
		abilities.put("Dry Skin", 43);
		abilities.put("Early Bird", 44);
		abilities.put("Effect Spore", 45);
		abilities.put("Electric Surge", 46);
		abilities.put("Emergency Exit", 47);
		abilities.put("Fairy Aura", 48);
		abilities.put("Filter", 49);
		abilities.put("Flame Body", 50);
		abilities.put("Flare Boost", 51);
		abilities.put("Flash Fire", 52);
		abilities.put("Flower Gift", 53);
		abilities.put("Flower Veil", 54);
		abilities.put("Fluffy", 55);
		abilities.put("Forecast", 56);
		abilities.put("Forewarn", 57);
		abilities.put("Friend Guard", 58);
		abilities.put("Frisk", 59);
		abilities.put("Full Metal Body", 60);
		abilities.put("Fur Coat", 61);
		abilities.put("Gale Wings", 62);
		abilities.put("Galvanize", 63);
		abilities.put("Gluttony", 64);
		abilities.put("Gooey", 65);
		abilities.put("Grass Pelt", 66);
		abilities.put("Grassy Surge", 67);
		abilities.put("Guts", 68);
		abilities.put("Harvest", 69);
		abilities.put("Healer", 70);
		abilities.put("Heatproof", 71);
		abilities.put("Heavy Metal", 72);
		abilities.put("Honey Gather", 73);
		abilities.put("Huge Power", 74);
		abilities.put("Hustle", 75);
		abilities.put("Hydration", 76);
		abilities.put("Hyper Cutter", 77);
		abilities.put("Ice Body", 78);
		abilities.put("Illuminate", 79);
		abilities.put("Illusion", 80);
		abilities.put("Immunity", 81);
		abilities.put("Imposter", 82);
		abilities.put("Infiltrator", 83);
		abilities.put("Innards Out", 84);
		abilities.put("Inner Focus", 85);
		abilities.put("Insomnia", 86);
		abilities.put("Intimidate", 87);
		abilities.put("Iron Barbs", 88);
		abilities.put("Iron Fist", 89);
		abilities.put("Justified", 90);
		abilities.put("Keen Eye", 91);
		abilities.put("Klutz", 92);
		abilities.put("Leaf Guard", 93);
		abilities.put("Levitate", 94);
		abilities.put("Light Metal", 95);
		abilities.put("Lightning Rod", 96);
		abilities.put("Limber", 97);
		abilities.put("Liquid Ooze", 98);
		abilities.put("Liquid Voice", 99);
		abilities.put("Long Reach", 100);
		abilities.put("Magic Bounce", 101);
		abilities.put("Magic Guard", 102);
		abilities.put("Magician", 103);
		abilities.put("Magma Armor", 104);
		abilities.put("Magnet Pull", 105);
		abilities.put("Marvel Scale", 106);
		abilities.put("Mega Launcher", 107);
		abilities.put("Merciless", 108);
		abilities.put("Minus", 109);
		abilities.put("Misty Surge", 110);
		abilities.put("Mold Breaker", 111);
		abilities.put("Moody", 112);
		abilities.put("Motor Drive", 113);
		abilities.put("Mountaineer", 114);
		abilities.put("Moxie", 115);
		abilities.put("Multiscale", 116);
		abilities.put("Multitype", 117);
		abilities.put("Mummy", 118);
		abilities.put("Natural Cure", 119);
		abilities.put("Neuroforce", 120);
		abilities.put("No Guard", 121);
		abilities.put("Normalize", 122);
		abilities.put("Oblivious", 123);
		abilities.put("Overcoat", 124);
		abilities.put("Overgrow", 125);
		abilities.put("Own Tempo", 126);
		abilities.put("Parental Bond", 127);
		abilities.put("Persistent", 128);
		abilities.put("Pickpocket", 129);
		abilities.put("Pickup", 130);
		abilities.put("Pixilate", 131);
		abilities.put("Plus", 132);
		abilities.put("Poison Heal", 133);
		abilities.put("Poison Point", 134);
		abilities.put("Poison Touch", 135);
		abilities.put("Power Construct", 136);
		abilities.put("Power of Alchemy", 137);
		abilities.put("Prankster", 138);
		abilities.put("Pressure", 139);
		abilities.put("Primordial Sea", 140);
		abilities.put("Prism Armor", 141);
		abilities.put("Protean", 142);
		abilities.put("Psychic Surge", 143);
		abilities.put("Pure Power", 144);
		abilities.put("Queenly Majesty", 145);
		abilities.put("Quick Feet", 146);
		abilities.put("RKS System", 147);
		abilities.put("Rain Dish", 148);
		abilities.put("Rattled", 149);
		abilities.put("Rebound", 150);
		abilities.put("Receiver", 151);
		abilities.put("Reckless", 152);
		abilities.put("Refrigerate", 153);
		abilities.put("Regenerator", 154);
		abilities.put("Rivalry", 155);
		abilities.put("Rock Head", 156);
		abilities.put("Rough Skin", 157);
		abilities.put("Run Away", 158);
		abilities.put("Sand Force", 159);
		abilities.put("Sand Rush", 160);
		abilities.put("Sand Stream", 161);
		abilities.put("Sand Veil", 162);
		abilities.put("Sap Sipper", 163);
		abilities.put("Schooling", 164);
		abilities.put("Scrappy", 165);
		abilities.put("Serene Grace", 166);
		abilities.put("Shadow Shield", 167);
		abilities.put("Shadow Tag", 168);
		abilities.put("Shed Skin", 169);
		abilities.put("Sheer Force", 170);
		abilities.put("Shell Armor", 171);
		abilities.put("Shield Dust", 172);
		abilities.put("Shields Down", 173);
		abilities.put("Simple", 174);
		abilities.put("Skill Link", 175);
		abilities.put("Slow Start", 176);
		abilities.put("Slush Rush", 177);
		abilities.put("Sniper", 178);
		abilities.put("Snow Cloak", 179);
		abilities.put("Snow Warning", 180);
		abilities.put("Solar Power", 181);
		abilities.put("Solid Rock", 182);
		abilities.put("Soul-Heart", 183);
		abilities.put("Soundproof", 184);
		abilities.put("Speed Boost", 185);
		abilities.put("Stakeout", 186);
		abilities.put("Stall", 187);
		abilities.put("Stamina", 188);
		abilities.put("Stance Change", 189);
		abilities.put("Static", 190);
		abilities.put("Steadfast", 191);
		abilities.put("Steelworker", 192);
		abilities.put("Stench", 193);
		abilities.put("Sticky Hold", 194);
		abilities.put("Storm Drain", 195);
		abilities.put("Strong Jaw", 196);
		abilities.put("Sturdy", 197);
		abilities.put("Suction Cups", 198);
		abilities.put("Super Luck", 199);
		abilities.put("Surge Surfer", 200);
		abilities.put("Swarm", 201);
		abilities.put("Sweet Veil", 202);
		abilities.put("Swift Swim", 203);
		abilities.put("Symbiosis", 204);
		abilities.put("Synchronize", 205);
		abilities.put("Tangled Feet", 206);
		abilities.put("Tangling Hair", 207);
		abilities.put("Technician", 208);
		abilities.put("Telepathy", 209);
		abilities.put("Teravolt", 210);
		abilities.put("Thick Fat", 211);
		abilities.put("Tinted Lens", 212);
		abilities.put("Torrent", 213);
		abilities.put("Tough Claws", 214);
		abilities.put("Toxic Boost", 215);
		abilities.put("Trace", 216);
		abilities.put("Triage", 217);
		abilities.put("Truant", 218);
		abilities.put("Turboblaze", 219);
		abilities.put("Unaware", 220);
		abilities.put("Unburden", 221);
		abilities.put("Unnerve", 222);
		abilities.put("Victory Star", 223);
		abilities.put("Vital Spirit", 224);
		abilities.put("Volt Absorb", 225);
		abilities.put("Water Absorb", 226);
		abilities.put("Water Bubble", 227);
		abilities.put("Water Compaction", 228);
		abilities.put("Water Veil", 229);
		abilities.put("Weak Armor", 230);
		abilities.put("White Smoke", 231);
		abilities.put("Wimp Out", 232);
		abilities.put("Wonder Guard", 233);
		abilities.put("Wonder Skin", 234);
		abilities.put("Zen Mode", 235);
	}
}
