package superDamageCalculator;

/* Associates an item with a particular number. Mostly for the
Item combobox, CalculateDamage handles the actual effects.
TODO: Refactor the item parser to weed out completely useless
items like Poke Balls.*/

import java.util.HashMap;

public class Itemdex
{
	public HashMap<String, Integer> items = new HashMap<String, Integer>();

	public Itemdex()
	{
		init();
	}

	public void init()
	{
		items.put("Abomasite", 0);
		items.put("Absolite", 1);
		items.put("Absorb Bulb", 2);
		items.put("Adamant Orb", 3);
		items.put("Adrenaline Orb", 4);
		items.put("Aerodactylite", 5);
		items.put("Aggronite", 6);
		items.put("Aguav Berry", 7);
		items.put("Air Balloon", 8);
		items.put("Alakazite", 9);
		items.put("Aloraichium Z", 10);
		items.put("Altarianite", 11);
		items.put("Ampharosite", 12);
		items.put("Apicot Berry", 13);
		items.put("Armor Fossil", 14);
		items.put("Aspear Berry", 15);
		items.put("Assault Vest", 16);
		items.put("Audinite", 17);
		items.put("Babiri Berry", 18);
		items.put("Banettite", 19);
		items.put("Beast Ball", 20);
		items.put("Beedrillite", 21);
		items.put("Belue Berry", 22);
		items.put("Berry", 23);
		items.put("Berry Juice", 24);
		items.put("Berserk Gene", 25);
		items.put("Big Root", 26);
		items.put("Binding Band", 27);
		items.put("Bitter Berry", 28);
		items.put("Black Belt", 29);
		items.put("Black Glasses", 30);
		items.put("Black Sludge", 31);
		items.put("Blastoisinite", 32);
		items.put("Blazikenite", 33);
		items.put("Blue Orb", 34);
		items.put("Bluk Berry", 35);
		items.put("BrightPowder", 36);
		items.put("Bug Gem", 37);
		items.put("Bug Memory", 38);
		items.put("Buginium Z", 39);
		items.put("Burn Drive", 40);
		items.put("Burnt Berry", 41);
		items.put("Cameruptite", 42);
		items.put("Cell Battery", 43);
		items.put("Charcoal", 44);
		items.put("Charizardite X", 45);
		items.put("Charizardite Y", 46);
		items.put("Charti Berry", 47);
		items.put("Cheri Berry", 48);
		items.put("Cherish Ball", 49);
		items.put("Chesto Berry", 50);
		items.put("Chilan Berry", 51);
		items.put("Chill Drive", 52);
		items.put("Choice Band", 53);
		items.put("Choice Scarf", 54);
		items.put("Choice Specs", 55);
		items.put("Chople Berry", 56);
		items.put("Claw Fossil", 57);
		items.put("Coba Berry", 58);
		items.put("Colbur Berry", 59);
		items.put("Cornn Berry", 60);
		items.put("Cover Fossil", 61);
		items.put("Crucibellite", 62);
		items.put("Custap Berry", 63);
		items.put("Damp Rock", 64);
		items.put("Dark Gem", 65);
		items.put("Dark Memory", 66);
		items.put("Darkinium Z", 67);
		items.put("Dawn Stone", 68);
		items.put("Decidium Z", 69);
		items.put("Deep Sea Scale", 70);
		items.put("Deep Sea Tooth", 71);
		items.put("Destiny Knot", 72);
		items.put("Diancite", 73);
		items.put("Dive Ball", 74);
		items.put("Dome Fossil", 75);
		items.put("Douse Drive", 76);
		items.put("Draco Plate", 77);
		items.put("Dragon Fang", 78);
		items.put("Dragon Gem", 79);
		items.put("Dragon Memory", 80);
		items.put("Dragon Scale", 81);
		items.put("Dragonium Z", 82);
		items.put("Dread Plate", 83);
		items.put("Dream Ball", 84);
		items.put("Dubious Disc", 85);
		items.put("Durin Berry", 86);
		items.put("Dusk Ball", 87);
		items.put("Dusk Stone", 88);
		items.put("Earth Plate", 89);
		items.put("Eevium Z", 90);
		items.put("Eject Button", 91);
		items.put("Electirizer", 92);
		items.put("Electric Gem", 93);
		items.put("Electric Memory", 94);
		items.put("Electric Seed", 95);
		items.put("Electrium Z", 96);
		items.put("Energy Powder", 97);
		items.put("Enigma Berry", 98);
		items.put("Eviolite", 99);
		items.put("Expert Belt", 100);
		items.put("Fairium Z", 101);
		items.put("Fairy Gem", 102);
		items.put("Fairy Memory", 103);
		items.put("Fast Ball", 104);
		items.put("Fighting Gem", 105);
		items.put("Fighting Memory", 106);
		items.put("Fightinium Z", 107);
		items.put("Figy Berry", 108);
		items.put("Fire Gem", 109);
		items.put("Fire Memory", 110);
		items.put("Fire Stone", 111);
		items.put("Firium Z", 112);
		items.put("Fist Plate", 113);
		items.put("Flame Orb", 114);
		items.put("Flame Plate", 115);
		items.put("Float Stone", 116);
		items.put("Flying Gem", 117);
		items.put("Flying Memory", 118);
		items.put("Flyinium Z", 119);
		items.put("Focus Band", 120);
		items.put("Focus Sash", 121);
		items.put("Friend Ball", 122);
		items.put("Full Incense", 123);
		items.put("Galladite", 124);
		items.put("Ganlon Berry", 125);
		items.put("Garchompite", 126);
		items.put("Gardevoirite", 127);
		items.put("Gengarite", 128);
		items.put("Ghost Gem", 129);
		items.put("Ghost Memory", 130);
		items.put("Ghostium Z", 131);
		items.put("Glalitite", 132);
		items.put("Gold Berry", 133);
		items.put("Grass Gem", 134);
		items.put("Grass Memory", 135);
		items.put("Grassium Z", 136);
		items.put("Grassy Seed", 137);
		items.put("Great Ball", 138);
		items.put("Grepa Berry", 139);
		items.put("Grip Claw", 140);
		items.put("Griseous Orb", 141);
		items.put("Ground Gem", 142);
		items.put("Ground Memory", 143);
		items.put("Groundium Z", 144);
		items.put("Gyaradosite", 145);
		items.put("Haban Berry", 146);
		items.put("Hard Stone", 147);
		items.put("Heal Ball", 148);
		items.put("Heat Rock", 149);
		items.put("Heavy Ball", 150);
		items.put("Helix Fossil", 151);
		items.put("Heracronite", 152);
		items.put("Hondew Berry", 153);
		items.put("Houndoominite", 154);
		items.put("Iapapa Berry", 155);
		items.put("Ice Berry", 156);
		items.put("Ice Gem", 157);
		items.put("Ice Memory", 158);
		items.put("Ice Stone", 159);
		items.put("Icicle Plate", 160);
		items.put("Icium Z", 161);
		items.put("Icy Rock", 162);
		items.put("Incinium Z", 163);
		items.put("Insect Plate", 164);
		items.put("Iron Ball", 165);
		items.put("Iron Plate", 166);
		items.put("Jaboca Berry", 167);
		items.put("Jaw Fossil", 168);
		items.put("Kangaskhanite", 169);
		items.put("Kasib Berry", 170);
		items.put("Kebia Berry", 171);
		items.put("Kee Berry", 172);
		items.put("Kelpsy Berry", 173);
		items.put("King's Rock", 174);
		items.put("Kommonium Z", 175);
		items.put("Lagging Tail", 176);
		items.put("Lansat Berry", 177);
		items.put("Latiasite", 178);
		items.put("Latiosite", 179);
		items.put("Lax Incense", 180);
		items.put("Leaf Stone", 181);
		items.put("Leftovers", 182);
		items.put("Leppa Berry", 183);
		items.put("Level Ball", 184);
		items.put("Liechi Berry", 185);
		items.put("Life Orb", 186);
		items.put("Light Ball", 187);
		items.put("Light Clay", 188);
		items.put("Lopunnite", 189);
		items.put("Love Ball", 190);
		items.put("Lucarionite", 191);
		items.put("Lucky Punch", 192);
		items.put("Lum Berry", 193);
		items.put("Luminous Moss", 194);
		items.put("Lunalium Z", 195);
		items.put("Lure Ball", 196);
		items.put("Lustrous Orb", 197);
		items.put("Luxury Ball", 198);
		items.put("Lycanium Z", 199);
		items.put("Macho Brace", 200);
		items.put("Magmarizer", 201);
		items.put("Magnet", 202);
		items.put("Mago Berry", 203);
		items.put("Magost Berry", 204);
		items.put("Mail", 205);
		items.put("Manectite", 206);
		items.put("Maranga Berry", 207);
		items.put("Marshadium Z", 208);
		items.put("Master Ball", 209);
		items.put("Mawilite", 210);
		items.put("Meadow Plate", 211);
		items.put("Medichamite", 212);
		items.put("Mental Herb", 213);
		items.put("Metagrossite", 214);
		items.put("Metal Coat", 215);
		items.put("Metal Powder", 216);
		items.put("Metronome", 217);
		items.put("Mewnium Z", 218);
		items.put("Mewtwonite X", 219);
		items.put("Mewtwonite Y", 220);
		items.put("Micle Berry", 221);
		items.put("Mimikium Z", 222);
		items.put("Mind Plate", 223);
		items.put("Mint Berry", 224);
		items.put("Miracle Berry", 225);
		items.put("Miracle Seed", 226);
		items.put("Misty Seed", 227);
		items.put("Moon Ball", 228);
		items.put("Moon Stone", 229);
		items.put("Muscle Band", 230);
		items.put("Mystery Berry", 231);
		items.put("Mystic Water", 232);
		items.put("Nanab Berry", 233);
		items.put("Nest Ball", 234);
		items.put("Net Ball", 235);
		items.put("Never-Melt Ice", 236);
		items.put("Nomel Berry", 237);
		items.put("Normal Gem", 238);
		items.put("Normalium Z", 239);
		items.put("Occa Berry", 240);
		items.put("Odd Incense", 241);
		items.put("Old Amber", 242);
		items.put("Oran Berry", 243);
		items.put("Oval Stone", 244);
		items.put("PRZ Cure Berry", 245);
		items.put("PSN Cure Berry", 246);
		items.put("Pamtre Berry", 247);
		items.put("Park Ball", 248);
		items.put("Passho Berry", 249);
		items.put("Payapa Berry", 250);
		items.put("Pecha Berry", 251);
		items.put("Persim Berry", 252);
		items.put("Petaya Berry", 253);
		items.put("Pidgeotite", 254);
		items.put("Pikanium Z", 255);
		items.put("Pikashunium Z", 256);
		items.put("Pinap Berry", 257);
		items.put("Pink Bow", 258);
		items.put("Pinsirite", 259);
		items.put("Pixie Plate", 260);
		items.put("Plume Fossil", 261);
		items.put("Poison Barb", 262);
		items.put("Poison Gem", 263);
		items.put("Poison Memory", 264);
		items.put("Poisonium Z", 265);
		items.put("Poke Ball", 266);
		items.put("Polkadot Bow", 267);
		items.put("Pomeg Berry", 268);
		items.put("Power Anklet", 269);
		items.put("Power Band", 270);
		items.put("Power Belt", 271);
		items.put("Power Bracer", 272);
		items.put("Power Herb", 273);
		items.put("Power Lens", 274);
		items.put("Power Weight", 275);
		items.put("Premier Ball", 276);
		items.put("Primarium Z", 277);
		items.put("Prism Scale", 278);
		items.put("Protective Pads", 279);
		items.put("Protector", 280);
		items.put("Psychic Gem", 281);
		items.put("Psychic Memory", 282);
		items.put("Psychic Seed", 283);
		items.put("Psychium Z", 284);
		items.put("Qualot Berry", 285);
		items.put("Quick Ball", 286);
		items.put("Quick Claw", 287);
		items.put("Quick Powder", 288);
		items.put("Rabuta Berry", 289);
		items.put("Rare Bone", 290);
		items.put("Rawst Berry", 291);
		items.put("Razor Claw", 292);
		items.put("Razor Fang", 293);
		items.put("Razz Berry", 294);
		items.put("Reaper Cloth", 295);
		items.put("Red Card", 296);
		items.put("Red Orb", 297);
		items.put("Repeat Ball", 298);
		items.put("Rindo Berry", 299);
		items.put("Ring Target", 300);
		items.put("Rock Gem", 301);
		items.put("Rock Incense", 302);
		items.put("Rock Memory", 303);
		items.put("Rockium Z", 304);
		items.put("Rocky Helmet", 305);
		items.put("Root Fossil", 306);
		items.put("Rose Incense", 307);
		items.put("Roseli Berry", 308);
		items.put("Rowap Berry", 309);
		items.put("Sablenite", 310);
		items.put("Sachet", 311);
		items.put("Safari Ball", 312);
		items.put("Safety Goggles", 313);
		items.put("Sail Fossil", 314);
		items.put("Salac Berry", 315);
		items.put("Salamencite", 316);
		items.put("Sceptilite", 317);
		items.put("Scizorite", 318);
		items.put("Scope Lens", 319);
		items.put("Sea Incense", 320);
		items.put("Sharp Beak", 321);
		items.put("Sharpedonite", 322);
		items.put("Shed Shell", 323);
		items.put("Shell Bell", 324);
		items.put("Shiny Stone", 325);
		items.put("Shock Drive", 326);
		items.put("Shuca Berry", 327);
		items.put("Silk Scarf", 328);
		items.put("SilverPowder", 329);
		items.put("Sitrus Berry", 330);
		items.put("Skull Fossil", 331);
		items.put("Sky Plate", 332);
		items.put("Slowbronite", 333);
		items.put("Smooth Rock", 334);
		items.put("Snorlium Z", 335);
		items.put("Snowball", 336);
		items.put("Soft Sand", 337);
		items.put("Solganium Z", 338);
		items.put("Soul Dew", 339);
		items.put("Spell Tag", 340);
		items.put("Spelon Berry", 341);
		items.put("Splash Plate", 342);
		items.put("Spooky Plate", 343);
		items.put("Sport Ball", 344);
		items.put("Starf Berry", 345);
		items.put("Steel Gem", 346);
		items.put("Steel Memory", 347);
		items.put("Steelium Z", 348);
		items.put("Steelixite", 349);
		items.put("Stick", 350);
		items.put("Sticky Barb", 351);
		items.put("Stone Plate", 352);
		items.put("Sun Stone", 353);
		items.put("Swampertite", 354);
		items.put("Tamato Berry", 355);
		items.put("Tanga Berry", 356);
		items.put("Tapunium Z", 357);
		items.put("Terrain Extender", 358);
		items.put("Thick Club", 359);
		items.put("Thunder Stone", 360);
		items.put("Timer Ball", 361);
		items.put("Toxic Orb", 362);
		items.put("Toxic Plate", 363);
		items.put("Twisted Spoon", 364);
		items.put("Tyranitarite", 365);
		items.put("Ultra Ball", 366);
		items.put("Ultranecrozium Z", 367);
		items.put("Up-Grade", 368);
		items.put("Venusaurite", 369);
		items.put("Wacan Berry", 370);
		items.put("Water Gem", 371);
		items.put("Water Memory", 372);
		items.put("Water Stone", 373);
		items.put("Waterium Z", 374);
		items.put("Watmel Berry", 375);
		items.put("Wave Incense", 376);
		items.put("Weakness Policy", 377);
		items.put("Wepear Berry", 378);
		items.put("Whipped Dream", 379);
		items.put("White Herb", 380);
		items.put("Wide Lens", 381);
		items.put("Wiki Berry", 382);
		items.put("Wise Glasses", 383);
		items.put("Yache Berry", 384);
		items.put("Zap Plate", 385);
		items.put("Zoom Lens", 386);
		items.put("(none)", 387);
	}
}
